name: Workflow Demo

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: List file
      run: ls
    - name: Test file
      run: cat hello.txt | grep -i "Hello, world!"